### ISSUE TITLE
Error when SourcesLocation has no subfolders

### ISSUE THREAD

**Issue by Tuttu** [codaamok/Get-CMUnusedSources#6]
Hello, 

When the script is launched against a folder that has no subfolders, the following error is thrown: 
```Impossible to call method with Null expression.
At character C:\Scripts\Divers\Get-CMUnusedSourcesDev.ps1:716 : 5
+     $Folders.Add($Path)
+     ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```
In addition, the console returns that the number of gathered folders is equal to 0, implying the root folder mentioned in the `SourcesLocation` parameter is not counted.

**Comment by codaamok** [comment]
Thanks @Tuttu I've committed a fix to address this in `develop` branch. May you give it a shot please? :-)

https://github.com/codaamok/Get-CMUnusedSources/tree/develop

**Comment by Tuttu** [comment]
The issue is not completely fixed. 
If scanning a single folder with no subfolders, the root folder (The one mentioned with `-SourcesLocation`) is now counted. Howerver, if this folder is unused, it's size is not counted and the Disk Space not used is of 0MB.
```
Content objects: 2531
Folders at \\ServerName\sources$\Installs\Versions Windows 7\6-Application CITRIX: 1
Folders where access denied: 0
Folders unused: 1
Disk space in "\\ServerName\sources$\Installs\Versions Windows 7\6-Application CITRIX" not used by ConfigMgr content objects (Package, Application, Driver, DriverPackage, OperatingSystemImage, OperatingSystemInstaller, BootImage, SoftwareUpdateDeploymentPackage): 0 MB
Runtime: 00:30:47.4094906
```

**Comment by codaamok** [comment]
Thanks @Tuttu ! That is also corrected :-)
